services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    build:
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file: ".env"
    volumes:
      - db_data:/var/lib/mysql

  create-project:
    env_file: ".env"
    image: composer:latest
    command:
      - sh
      - -c
      - |
        composer --ignore-platform-reqs create-project laravel/laravel /var/www/laravel
        addgroup -g $GID $GROUPNAME
        adduser -D -g '' -h /home/$GROUPNAME -G $GROUPNAME -u $UID $USER
        chown -R $USER:$USER /var/www/laravel
        chmod -R 777 /var/www/laravel/storage
    volumes:
      - ./src:/var/www/laravel

  db-init:
    build:
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
    command:
      - sh
      - -c
      - |
        sed -i '/DB_CONNECTION/d' '.env'
        sed -i '/DB_HOST/d' '.env'
        sed -i '/DB_PORT/d' '.env'
        sed -i '/DB_DATABASE/d' '.env'
        sed -i '/DB_USERNAME/d' '.env'
        sed -i '/DB_PASSWORD/d' '.env'
        tee -a /var/www/laravel/.env << EOF
        DB_CONNECTION=mysql
        DB_HOST=mysql
        DB_PORT=3306
        DB_DATABASE=$MYSQL_DATABASE
        DB_USERNAME=$MYSQL_USER
        DB_PASSWORD=$MYSQL_PASSWORD
        EOF
        php /var/www/laravel/artisan migrate

volumes:
  db_data:

